spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log


#  # Redis数据库索引（默认为0）
#  spring.redis.database=0
#  # Redis服务器地址
#  spring.redis.host=192.168.0.24
#  # Redis服务器连接端口
#  spring.redis.port=6379
#  # Redis服务器连接密码（默认为空）
#  spring.redis.password=
#  # 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.pool.max-active=200
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.pool.max-idle=10
#  # 连接池中的最小空闲连接
#  spring.redis.pool.min-idle=0
#  # 连接超时时间（毫秒）
#  spring.redis.timeout=1000




